dist: xenial   # required for Python >= 3.7
os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
#  - pip install psychrochart
  - pip install .
  - pip install coverage==4.5.3
  - pip install pytest==4.4.1 pytest-cov==2.6.1
  - pip install coveralls==1.7.0

script:
  - py.test -v --cov psychrochart --cov-report term-missing
after_sucess:
  - coveralls
